## 모두의 딥러닝 개정3판
### 17장 딥러닝을 이용한 자연어처리

In [1]:
from tensorflow.keras import models, layers
from tensorflow.keras.preprocessing.text import Tokenizer, text_to_word_sequence
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

import numpy as np

In [2]:
text = '해보지 않으면 해낼 수 없다'

# text_to_word_sequence()함수 = 띄어쓰기를 기준으로 쪼개줌
result = text_to_word_sequence(text)
print("원문 : ", text)
print("토큰화 : ", result)

원문 :  해보지 않으면 해낼 수 없다
토큰화 :  ['해보지', '않으면', '해낼', '수', '없다']


In [3]:
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화 합니다.',
       '텍스트의 단어로 토큰화해야 딥러닝에서 인식됩니다.',
       '토큰화한 결과는 딥러닝에서 사용할 수 있습니다.',
       ]

token = Tokenizer() # 토큰화 함수 지정
token.fit_on_texts(docs) # 토큰화 함수에 문장 적용

In [4]:
print(token.word_counts) # 단어의 빈도수를 계산한 결과 출력

OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화', 1), ('합니다', 1), ('단어로', 1), ('토큰화해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('토큰화한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])


In [5]:
print(token.document_count) # 문장 카운트

3


In [6]:
print(token.word_docs) # 각 단어가 몇 개의 문장에 포함되어 있는가

defaultdict(<class 'int'>, {'단어를': 1, '토큰화': 1, '나누어': 1, '각': 1, '텍스트의': 2, '먼저': 1, '합니다': 1, '토큰화해야': 1, '인식됩니다': 1, '딥러닝에서': 2, '단어로': 1, '토큰화한': 1, '있습니다': 1, '사용할': 1, '결과는': 1, '수': 1})


In [7]:
print(token.word_index) # 각 단어에 매겨진 인덱스 값

{'텍스트의': 1, '딥러닝에서': 2, '먼저': 3, '각': 4, '단어를': 5, '나누어': 6, '토큰화': 7, '합니다': 8, '단어로': 9, '토큰화해야': 10, '인식됩니다': 11, '토큰화한': 12, '결과는': 13, '사용할': 14, '수': 15, '있습니다': 16}


In [8]:
text="오랫동안 꿈꾸는 이는 그 꿈을 닮아간다"

token = Tokenizer()
token.fit_on_texts([text])

print(token.word_index)

{'오랫동안': 1, '꿈꾸는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}


In [9]:
x=token.texts_to_sequences([text]) # 원-핫 인코딩(one-hot encoding)을 하기위해 각 단어를 풀어줌
print(x)

[[1, 2, 3, 4, 5, 6]]


In [10]:
# 인덱스 수에 하나를 추가해서 원-핫 인코딩 배열 만들기

word_size = len(token.word_index) + 1 # 단어는 배열이 1부터 시작이기때문에 1을 추가해줘야한다
x = to_categorical(x, num_classes=word_size) # num_classes를 x만큼만 해주는게 아닌 +1을 추가해야하기때문에

print(x)

[[[0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 1.]]]


In [11]:
# 텍스트 리뷰 자료를 지정합니다.
docs = ["너무 재밌네요",
        "최고예요",
        "참 잘 만든 영화예요",
        "추천하고 싶은 영화입니다",
        "한번 더 보고싶네요",
        "글쎄요",
        "별로예요",
        "생각보다 지루하네요",
        "연기가 어색해요",
        "재미없어요"]

# 긍정 리뷰는 1, 부정 리뷰는 0으로 클래스를 지정합니다.
classes = np.array([1,1,1,1,1,0,0,0,0,0])

In [12]:
token = Tokenizer()
token.fit_on_texts(docs)

print(token.word_index) # 토큰 결과를 출력

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}


In [13]:
x = token.texts_to_sequences(docs)

# 각 문장(배열)마다 길이가 다름...
print(x)

[[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]


In [14]:
# 길이를 똑같이 맞춰주는 작업 = padding
padded_x = pad_sequences(x, 4) # 서로 다른 길이의 데이터를 4로 맞추기

print(padded_x)

[[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]


In [15]:
word_size = len(token.word_index) + 1
model = models.Sequential()

# Embedding() 레이어 = 각 단어별로 차원을 구성하면 단어 수 만큼의 차원을 구성해야함
# 이건 너무 비효율적이므로 단어마다 비슷한 성향이 있는 것은 가까운 차원에 있을것이라는 이론에 기반해서
# 저차원으로 구성된 모델을 제공하는 함수
model.add(layers.Embedding(word_size, 8, input_length=4)) # 8차원으로 줄여줬음
model.add(layers.Flatten())
model.add(layers.Dense(1, activation='sigmoid')) # 긍정이냐 부정이냐 이분법이므로 'sigmoid'
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 8)              168       
                                                                 
 flatten (Flatten)           (None, 32)                0         
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 201
Trainable params: 201
Non-trainable params: 0
_________________________________________________________________


In [16]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(padded_x, classes, epochs=20)

Epoch 1/20
1/1 [==============================] - 1s 772ms/step - loss: 0.6906 - accuracy: 0.6000
Epoch 2/20
1/1 [==============================] - 0s 4ms/step - loss: 0.6885 - accuracy: 0.6000
Epoch 3/20
1/1 [==============================] - 0s 5ms/step - loss: 0.6863 - accuracy: 0.6000
Epoch 4/20
1/1 [==============================] - 0s 4ms/step - loss: 0.6842 - accuracy: 0.6000
Epoch 5/20
1/1 [==============================] - 0s 4ms/step - loss: 0.6821 - accuracy: 0.8000
Epoch 6/20
1/1 [==============================] - 0s 5ms/step - loss: 0.6800 - accuracy: 0.8000
Epoch 7/20
1/1 [==============================] - 0s 4ms/step - loss: 0.6779 - accuracy: 0.8000
Epoch 8/20
1/1 [==============================] - 0s 10ms/step - loss: 0.6758 - accuracy: 0.8000
Epoch 9/20
1/1 [==============================] - 0s 9ms/step - loss: 0.6737 - accuracy: 0.8000
Epoch 10/20
1/1 [==============================] - 0s 4ms/step - loss: 0.6716 - accuracy: 0.8000
Epoch 11/20
1/1 [===================