In [1]:
import pandas as pd

In [2]:
s1 = pd.Series([10, 20, 30, 40, 50])
print(s1)

0    10
1    20
2    30
3    40
4    50
dtype: int64


### index | value(data)

In [3]:
print(s1.index)

RangeIndex(start=0, stop=5, step=1)


In [4]:
print(s1.values)

[10 20 30 40 50]


In [5]:
print(type(s1.values))

<class 'numpy.ndarray'>


In [6]:
s2 = pd.Series(['a', 'b', 'c', 1, 2, 3])
print(s2)

0    a
1    b
2    c
3    1
4    2
5    3
dtype: object


### type 섞어 쓸 일 없다

In [7]:
import numpy as np
s3 = pd.Series([np.nan, 1, 2])
print(s3)

0    NaN
1    1.0
2    2.0
dtype: float64


In [8]:
index_date = ['2020-03-20', '2020-03-21', '2020-03-22', '2020-03-23']
s4 = pd.Series([200, 187, np.nan, 210], index=index_date)
print(s4)

2020-03-20    200.0
2020-03-21    187.0
2020-03-22      NaN
2020-03-23    210.0
dtype: float64


In [9]:
s5 = pd.Series({'국어':100, '영어':95, '수학':100})
print(s5)

국어    100
영어     95
수학    100
dtype: int64


In [10]:
p = pd.date_range(start='2020-01-20', end='2020-01-27')
print(p)

DatetimeIndex(['2020-01-20', '2020-01-21', '2020-01-22', '2020-01-23',
               '2020-01-24', '2020-01-25', '2020-01-26', '2020-01-27'],
              dtype='datetime64[ns]', freq='D')


In [11]:
p = pd.date_range(start='2020/01/20', end='2020.01.27')
print(p)

DatetimeIndex(['2020-01-20', '2020-01-21', '2020-01-22', '2020-01-23',
               '2020-01-24', '2020-01-25', '2020-01-26', '2020-01-27'],
              dtype='datetime64[ns]', freq='D')


In [12]:
p = pd.date_range(start='2020-05-01', periods=7)
print(p)

DatetimeIndex(['2020-05-01', '2020-05-02', '2020-05-03', '2020-05-04',
               '2020-05-05', '2020-05-06', '2020-05-07'],
              dtype='datetime64[ns]', freq='D')


In [13]:
p = pd.date_range(start='2020-01-01', periods=4, freq='2D')
print(p)

DatetimeIndex(['2020-01-01', '2020-01-03', '2020-01-05', '2020-01-07'], dtype='datetime64[ns]', freq='2D')


In [14]:
p = pd.date_range(start='2022-01-01', periods=5, freq='W')
print(p)

DatetimeIndex(['2022-01-02', '2022-01-09', '2022-01-16', '2022-01-23',
               '2022-01-30'],
              dtype='datetime64[ns]', freq='W-SUN')


In [16]:
p = pd.date_range(start='2022-01-01', periods=5, freq='W-MON')
print(p)

DatetimeIndex(['2022-01-03', '2022-01-10', '2022-01-17', '2022-01-24',
               '2022-01-31'],
              dtype='datetime64[ns]', freq='W-MON')


In [17]:
p = pd.date_range(start='2023-02-01', periods=12, freq='2M')
print(p)

DatetimeIndex(['2023-02-28', '2023-04-30', '2023-06-30', '2023-08-31',
               '2023-10-31', '2023-12-31', '2024-02-29', '2024-04-30',
               '2024-06-30', '2024-08-31', '2024-10-31', '2024-12-31'],
              dtype='datetime64[ns]', freq='2M')


In [18]:
p = pd.date_range(start='2023-02-01', periods=12, freq='2BM')
print(p)

DatetimeIndex(['2023-02-28', '2023-04-28', '2023-06-30', '2023-08-31',
               '2023-10-31', '2023-12-29', '2024-02-29', '2024-04-30',
               '2024-06-28', '2024-08-30', '2024-10-31', '2024-12-31'],
              dtype='datetime64[ns]', freq='2BM')


### business day : 휴일 빼고 마지막 날

In [19]:
p = pd.date_range(start='2023-01-03', periods=4, freq='QS')
print(p)

DatetimeIndex(['2023-04-01', '2023-07-01', '2023-10-01', '2024-01-01'], dtype='datetime64[ns]', freq='QS-JAN')


### 분기별

In [20]:
p = pd.date_range(start='2020-01-01 08:00', periods=10, freq='H')
print(p)

DatetimeIndex(['2020-01-01 08:00:00', '2020-01-01 09:00:00',
               '2020-01-01 10:00:00', '2020-01-01 11:00:00',
               '2020-01-01 12:00:00', '2020-01-01 13:00:00',
               '2020-01-01 14:00:00', '2020-01-01 15:00:00',
               '2020-01-01 16:00:00', '2020-01-01 17:00:00'],
              dtype='datetime64[ns]', freq='H')


In [21]:
df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(df)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9


### 세로 : index 가로 : column

In [22]:
print(df.values)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
index_date = pd.date_range('2020-05-01', periods=4)
columns_list = ['A', 'B', 'C']
df = pd.DataFrame(data, index=index_date, columns=columns_list)
print(df)

             A   B   C
2020-05-01   1   2   3
2020-05-02   4   5   6
2020-05-03   7   8   9
2020-05-04  10  11  12


In [24]:
data = {'연도': [2015, 2016, 2016, 2017, 2017], '지사': ['서울', '서울', '부산', '서울', '부산'],
        '고객 수': [200, 250, 150, 300, 200]}
df = pd.DataFrame(data)
print(df)

     연도  지사  고객 수
0  2015  서울   200
1  2016  서울   250
2  2016  부산   150
3  2017  서울   300
4  2017  부산   200


### dictionary의 key 값 = column이름

In [25]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([10, 20, 30, 40, 50])
print(s1 + s2)
print(s2 - s1)
print(s1 * s2)
print(s2 / s1)

0    11
1    22
2    33
3    44
4    55
dtype: int64
0     9
1    18
2    27
3    36
4    45
dtype: int64
0     10
1     40
2     90
3    160
4    250
dtype: int64
0    10.0
1    10.0
2    10.0
3    10.0
4    10.0
dtype: float64


In [26]:
s3 = pd.Series([1, 2, 3, 4])
s4 = pd.Series([10, 20, 30, 40, 50])
print(s3 + s4)

0    11.0
1    22.0
2    33.0
3    44.0
4     NaN
dtype: float64


### numpy는 error / pandas = nan

In [27]:
data1 = {'A': [1, 2, 3, 4, 5],
         'B': [10, 20, 30, 40, 50],
         'C': [100, 200, 300, 400, 500]}
df1 = pd.DataFrame(data1)
print(df1)

data2 = {'A': [6, 7, 8],
         'B': [60, 70, 80],
         'C': [600, 700, 800]}
df2 = pd.DataFrame(data2)
print(df2)
print('='*20)
print(df1 + df2)

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500
   A   B    C
0  6  60  600
1  7  70  700
2  8  80  800
      A      B       C
0   7.0   70.0   700.0
1   9.0   90.0   900.0
2  11.0  110.0  1100.0
3   NaN    NaN     NaN
4   NaN    NaN     NaN


### shape이 달라 nan

In [28]:
table_data3 = {'봄':  [256.5, 264.3, 215.9, 223.2, 312.8],
              '여름': [770.6, 567.5, 599.8, 387.1, 446.2],
              '가을': [363.5, 231.2, 293.1, 247.7, 381.6],
              '겨울': [139.3, 59.9, 76.9, 109.1, 108.1]}
columns_list = ['봄', '여름', '가을', '겨울']
index_list = ['2012', '2013', '2014', '2015', '2016']

df3 = pd.DataFrame(table_data3, columns = columns_list, index = index_list)
print(df3)
print('='*30)
print(df3.mean()) # 계절별
print('='*30)
print(df3.std())  # 계절별
print('='*30)
print(df3.mean(axis=1)) # 연도별
print('='*30)
print(df3.std(axis=1)) # 연도별
print('='*30)
print(df3.describe())

          봄     여름     가을     겨울
2012  256.5  770.6  363.5  139.3
2013  264.3  567.5  231.2   59.9
2014  215.9  599.8  293.1   76.9
2015  223.2  387.1  247.7  109.1
2016  312.8  446.2  381.6  108.1
봄     254.54
여름    554.24
가을    303.42
겨울     98.66
dtype: float64
봄      38.628267
여름    148.888895
가을     67.358496
겨울     30.925523
dtype: float64
2012    382.475
2013    280.725
2014    296.425
2015    241.775
2016    312.175
dtype: float64
2012    274.472128
2013    211.128782
2014    221.150739
2015    114.166760
2016    146.548658
dtype: float64
                봄          여름          가을          겨울
count    5.000000    5.000000    5.000000    5.000000
mean   254.540000  554.240000  303.420000   98.660000
std     38.628267  148.888895   67.358496   30.925523
min    215.900000  387.100000  231.200000   59.900000
25%    223.200000  446.200000  247.700000   76.900000
50%    256.500000  567.500000  293.100000  108.100000
75%    264.300000  599.800000  363.500000  109.100000
max    312.8000

### describe = axis 0 (세로)에 대한 평균

In [29]:
KTX_data = {'경부선 KTX': [39060, 39896, 42005, 43621, 41702, 41266, 32427],
            '호남선 KTX': [7313, 6967, 6873, 6626, 8675, 10622, 9228],
            '경전선 KTX': [3627, 4168, 4088, 4424, 4606, 4984, 5570],
            '전라선 KTX': [309, 1771, 1954, 2244, 3146, 3945, 5766],
            '동해선 KTX': [np.nan,np.nan, np.nan, np.nan, 2395, 3786, 6667]}
col_list = ['경부선 KTX','호남선 KTX','경전선 KTX','전라선 KTX','동해선 KTX']
index_list = ['2011', '2012', '2013', '2014', '2015', '2016', '2017']

df_KTX = pd.DataFrame(KTX_data, columns = col_list, index = index_list)
print(df_KTX)

      경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2011    39060     7313     3627      309      NaN
2012    39896     6967     4168     1771      NaN
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0
2016    41266    10622     4984     3945   3786.0
2017    32427     9228     5570     5766   6667.0


In [32]:
df_KTX.head(2)

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2011    39060     7313     3627      309      NaN
2012    39896     6967     4168     1771      NaN

In [31]:
df_KTX.tail()

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0
2016    41266    10622     4984     3945   3786.0
2017    32427     9228     5570     5766   6667.0

In [33]:
print(df_KTX[1:2])

      경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2012    39896     6967     4168     1771      NaN


In [34]:
print(df_KTX[2:5])

      경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0


In [35]:
print(df_KTX.loc['2011'])

경부선 KTX    39060.0
호남선 KTX     7313.0
경전선 KTX     3627.0
전라선 KTX      309.0
동해선 KTX        NaN
Name: 2011, dtype: float64


### .loc = 해당 index의 series 객체

In [36]:
print(type(df_KTX.loc['2011']))

<class 'pandas.core.series.Series'>


In [37]:
print(df_KTX.loc['2013':'2016'])

      경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0
2016    41266    10622     4984     3945   3786.0


### 2016이 포함

In [38]:
print(df_KTX['경부선 KTX'])

2011    39060
2012    39896
2013    42005
2014    43621
2015    41702
2016    41266
2017    32427
Name: 경부선 KTX, dtype: int64


### 특정 column만 보고 싶을 때

In [39]:
print(df_KTX['경부선 KTX']['2012':'2014'])

2012    39896
2013    42005
2014    43621
Name: 경부선 KTX, dtype: int64


### 특정 column 로우만 보고 싶을 때

In [40]:
print(df_KTX['경부선 KTX'][1:4])

2012    39896
2013    42005
2014    43621
Name: 경부선 KTX, dtype: int64


In [41]:
print(df_KTX.loc['2016']['호남선 KTX'])
print('='*40)
print(df_KTX.loc['2016','호남선 KTX'])
print('='*40)
print(df_KTX['호남선 KTX']['2016'])
print('='*40)
print(df_KTX['호남선 KTX'][5])
print('='*40)
print(df_KTX['호남선 KTX'].loc['2016'])

10622.0
10622
10622
10622
10622


In [42]:
print(df_KTX.T)

            2011     2012     2013     2014     2015     2016     2017
경부선 KTX  39060.0  39896.0  42005.0  43621.0  41702.0  41266.0  32427.0
호남선 KTX   7313.0   6967.0   6873.0   6626.0   8675.0  10622.0   9228.0
경전선 KTX   3627.0   4168.0   4088.0   4424.0   4606.0   4984.0   5570.0
전라선 KTX    309.0   1771.0   1954.0   2244.0   3146.0   3945.0   5766.0
동해선 KTX      NaN      NaN      NaN      NaN   2395.0   3786.0   6667.0


In [43]:
print(df_KTX[['동해선 KTX', '전라선 KTX', '경전선 KTX', '호남선 KTX', '경부선 KTX']])

      동해선 KTX  전라선 KTX  경전선 KTX  호남선 KTX  경부선 KTX
2011      NaN      309     3627     7313    39060
2012      NaN     1771     4168     6967    39896
2013      NaN     1954     4088     6873    42005
2014      NaN     2244     4424     6626    43621
2015   2395.0     3146     4606     8675    41702
2016   3786.0     3945     4984    10622    41266
2017   6667.0     5766     5570     9228    32427


### column 순서를 바꾸고 싶을 때는 명시적으로 변경

DataFrame 통합

In [4]:
df1 = pd.DataFrame({'Class1': [95, 92, 98, 100],
                    'Class2': [91, 93, 97, 99]})
print(df1)

   Class1  Class2
0      95      91
1      92      93
2      98      97
3     100      99


In [5]:
df2 = pd.DataFrame({'Class1': [87, 89],'Class2': [85, 90]})

In [6]:
print(df2)

   Class1  Class2
0      87      85
1      89      90


In [7]:
print(df1.append(df2))

   Class1  Class2
0      95      91
1      92      93
2      98      97
3     100      99
0      87      85
1      89      90


C:\Users\BIT\AppData\Local\Temp\ipykernel_13368\1388991793.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  print(df1.append(df2))


In [8]:
print(df1.append(df2, ignore_index=True))

   Class1  Class2
0      95      91
1      92      93
2      98      97
3     100      99
4      87      85
5      89      90


C:\Users\BIT\AppData\Local\Temp\ipykernel_13368\231860784.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  print(df1.append(df2, ignore_index=True))


### ignore_index=True : index 무시하고 순서대로 출력

In [9]:
# print(df1.concat(df2, ignore_index=True))
print(pd.concat([df1, df2], ignore_index=True))

   Class1  Class2
0      95      91
1      92      93
2      98      97
3     100      99
4      87      85
5      89      90


In [10]:
df3 = pd.DataFrame({'Class1': [96, 83]})

In [11]:
print(df3)

   Class1
0      96
1      83


In [12]:
import pandas as pd
print(pd.concat([df2, df3], ignore_index=True))

   Class1  Class2
0      87    85.0
1      89    90.0
2      96     NaN
3      83     NaN


In [54]:
df4 = pd.DataFrame({'Class3': [93, 91, 95, 98]})
print(df4)

   Class3
0      93
1      91
2      95
3      98


In [55]:
print(df1)

   Class1  Class2
0      95      91
1      92      93
2      98      97
3     100      99


In [56]:
print(df1.join(df4))

   Class1  Class2  Class3
0      95      91      93
1      92      93      91
2      98      97      95
3     100      99      98


### 동일한 index 기준으로 좌우로 붙이는 것

In [57]:
df_A_B = pd.DataFrame({'판매월': ['1월', '2월', '3월', '4월'],
                       '제품A': [100, 150, 200, 130],
                       '제품B': [90, 110, 140, 170]})
print(df_A_B)

  판매월  제품A  제품B
0  1월  100   90
1  2월  150  110
2  3월  200  140
3  4월  130  170


In [58]:
df_C_D = pd.DataFrame({'판매월': ['1월', '2월', '3월', '4월'],
                   '제품C': [112, 141, 203, 134],
                   '제품D': [90, 110, 140, 170]})
print(df_C_D)

  판매월  제품C  제품D
0  1월  112   90
1  2월  141  110
2  3월  203  140
3  4월  134  170


In [59]:
print(df_A_B.merge(df_C_D))

  판매월  제품A  제품B  제품C  제품D
0  1월  100   90  112   90
1  2월  150  110  141  110
2  3월  200  140  203  140
3  4월  130  170  134  170


### merge : 동일한 column(판매월) 기준으로 붙이는 것

In [60]:
df_left = pd.DataFrame({'key':['A','B','C'], 'left': [1, 2, 3]})
print(df_left)
print('='*40)
df_right = pd.DataFrame({'key':['A','B','D'], 'right': [4, 5, 6]})
print(df_right)

  key  left
0   A     1
1   B     2
2   C     3
  key  right
0   A      4
1   B      5
2   D      6


In [61]:
print(df_left.merge(df_right, how='left', on = 'key'))

  key  left  right
0   A     1    4.0
1   B     2    5.0
2   C     3    NaN


In [62]:
print(df_left.merge(df_right, how='right', on = 'key'))

  key  left  right
0   A   1.0      4
1   B   2.0      5
2   D   NaN      6


In [63]:
print(df_left.merge(df_right, how='outer', on = 'key'))

  key  left  right
0   A   1.0    4.0
1   B   2.0    5.0
2   C   3.0    NaN
3   D   NaN    6.0


In [64]:
print(df_left.merge(df_right, how='inner', on = 'key')) # inner join 공통된 것

  key  left  right
0   A     1      4
1   B     2      5


In [65]:
df = pd.read_csv('data/sea_rain1.csv', encoding='cp949')
print(df)

     연도       동해       남해       서해       전체
0  1996  17.4629  17.2288  14.4360  15.9067
1  1997  17.4116  17.4092  14.8248  16.1526
2  1998  17.5944  18.0110  15.2512  16.6044
3  1999  18.1495  18.3175  14.8979  16.6284
4  2000  17.9288  18.1766  15.0504  16.6178


### csv파일 다운 받고 encoding값 주기

In [66]:
df = pd.read_csv('data/sea_rain1.csv', encoding='cp949', index_col="연도")
print(df)

           동해       남해       서해       전체
연도                                      
1996  17.4629  17.2288  14.4360  15.9067
1997  17.4116  17.4092  14.8248  16.1526
1998  17.5944  18.0110  15.2512  16.6044
1999  18.1495  18.3175  14.8979  16.6284
2000  17.9288  18.1766  15.0504  16.6178


### 연도 칼럼을 index로 잡기

In [71]:
df_WH = pd.DataFrame({'몸무게':[62, 67, 55, 74],
                      '키':[165, 177, 160, 180]},
                       index=['ID_1', 'ID_2', 'ID_3', 'ID_4'])
df_WH.index.name = 'User'
print(df_WH)

      몸무게    키
User          
ID_1   62  165
ID_2   67  177
ID_3   55  160
ID_4   74  180


In [72]:
df_WH['BMI'] = df_WH['몸무게']/(df_WH['키']/100)**2

In [73]:
print(df_WH)

      몸무게    키        BMI
User                     
ID_1   62  165  22.773186
ID_2   67  177  21.385936
ID_3   55  160  21.484375
ID_4   74  180  22.839506


### Dataframe에 column 추가하기

In [70]:
df_WH.to_csv('data/bmi.csv')

### 저장하기